author: Almaz Ibragimov
author_url: https://tech.hh.ru
github_url: https://github.com/hhru/Nivelir
copyright: '© 2022 [HeadHunter](https://tech.hh.ru) under the MIT license.'
module: Nivelir
output: docs
theme: fullwidth
clean: true
podspec: Nivelir.podspec
xcodebuild_arguments: [-workspace, 'Nivelir.xcworkspace', -scheme, 'Nivelir iOS']
hide_unlisted_documentation: true

custom_categories:
  - name: Screen
    children:
      - Screen
      - ScreenContainer
      - ScreenKey
      - ScreenKeyedContainer
      - ScreenVisibleContainer
      - ScreenIterableContainer
      - ScreenPayload
      - ScreenPayloadedContainer
      - AnyScreen
      - AnyModalScreen
      - AnyStackScreen
      - AnyTabsScreen

  - name: Route
    children:
      - ScreenThenable
      - ScreenRoute
      - ScreenRouteConvertible
      - ScreenRootRoute
      - ScreenModalRoute
      - ScreenStackRoute
      - ScreenTabsRoute
      - ScreenWindowRoute

  - name: Actions
    children:
      - ScreenAction
      - ScreenActionStorage
      - AnyScreenAction

      - ScreenFailAction
      - ScreenFoldAction
      - ScreenFromAction
      - ScreenGetAction
      - ScreenMakeVisibleAction
      - ScreenNavigateAction
      - ScreenWaitAction

      - ScreenPredicate
      - ScreenFirstAction
      - ScreenLastAction
      - ScreenTopAction

      - ScreenRefreshAction
      - ScreenRefreshableContainer

      - ScreenTryAction
      - ScreenTryResolution

      - ScreenDismissAction
      - ScreenPresentAction
      - ScreenPresentedAction
      - ScreenPresentingAction
      - ScreenStackAction
      - ScreenTabsAction
      - ScreenWindowAction

      - ScreenSetStackAction
      - ScreenStackModifier
      - ScreenStackClearModifier
      - ScreenStackPushModifier
      - ScreenStackReplaceModifier
      - ScreenStackPopModifier
      - ScreenStackPopPredicate
      - ScreenStackAnimation
      - ScreenStackCustomAnimation
      - ScreenStackTransitionAnimation
      - ScreenStackRootAction
      - ScreenStackTopAction
      - ScreenStackVisibleAction

      - ScreenSelectTabAction
      - ScreenTabAnimation
      - ScreenTabCustomAnimation
      - ScreenTabTransitionAnimation
      - ScreenTabPredicate
      - ScreenSelectedTabAction
      - ScreenSetupTabAction

      - ScreenMakeKeyAction
      - ScreenMakeKeyAndVisibleAction
      - ScreenRootAction
      - ScreenSetRootAction
      - ScreenRootAnimation
      - ScreenRootCustomAnimation
      - ScreenRootTransitionAnimation

  - name: Errors
    children:
      - ScreenError
      - ScreenCanceledError
      - ScreenContainerNotFoundError
      - ScreenContainerNotSupportedError
      - ScreenContainerTypeMismatchError

  - name: Observation
    children:
      - ScreenObservation
      - ScreenObserver
      - ScreenObserverPredicate
      - ScreenObserverToken

  - name: Navigator
    children:
      - ScreenNavigator
      - ScreenLogger
      - DefaultScreenLogger
      - ScreenIterator
      - DefaultScreenIterator
      - ScreenIterationResult
      - ScreenIterationPredicate
      - ScreenWindowProvider
      - ScreenKeyWindowProvider
      - ScreenCustomWindowProvider
      - ScreenObservatory
      - DefaultScreenObservatory

  - name: Deeplink
    children:
      - Deeplink
      - AnyDeeplink
      - DeeplinkManager
      - DeeplinkHandler
      - DeeplinkScope
      - DeeplinkType
      - DeeplinkInterceptor

      - DeeplinkError
      - DeeplinkInvalidContextError
      - DeeplinkInvalidRoutesError

      - NotificationDeeplink
      - NotificationDeeplinkUserInfoDecoder
      - NotificationDeeplinkUserInfoOptions
      - AnyNotificationDeeplink
      - NotificationDeeplinkInvalidUserInfoError

      - ShortcutDeeplink
      - ShortcutDeeplinkUserInfoDecoder
      - ShortcutDeeplinkUserInfoOptions
      - AnyShortcutDeeplink

      - URLDeeplink
      - URLDeeplinkQueryDecoder
      - URLDeeplinkQueryOptions
      - AnyURLDeeplink
      - URLDeeplinkInvalidComponentsError

  - name: Extensions
    children:
      - UIViewController
      - UINavigationController
      - UITabBarController
      - UIWindow

  - name: ActionSheet
    children:
      - ActionSheet
      - ActionSheetAction
      - ScreenShowActionSheetAction

  - name: Alert
    children:
      - Alert
      - AlertAction
      - AlertTextField
      - ScreenShowAlertAction

  - name: DocumentPreview
    children:
      - DocumentPreview
      - DocumentPreviewAnchor
      - ScreenShowDocumentPreviewAction

  - name: Haptics
    children:
      - ScreenImpactOccurredAction
      - ScreenNotificationOccurredAction
      - ScreenSelectionChangedAction

  - name: HUD
    children:
      - HUD
      - HUDStyle
      - HUDAnimation
      - HUDCustomAnimation
      - HUDDefaultAnimation
      - ScreenHideHUDAction
      - ScreenShowHUDAction

      - Progress
      - ProgressView

      - ProgressAnimation
      - ProgressCustomAnimation
      - ProgressDefaultAnimation

      - AnyProgressContent
      - ProgressContent
      - ProgressContentView

      - ProgressHeader
      - ProgressEmptyHeader
      - ProgressEmptyHeaderView

      - ProgressFooter
      - ProgressMessageFooter
      - ProgressMessageFooterView
      - ProgressEmptyFooter
      - ProgressEmptyFooterView

      - ProgressIndicator
      - ProgressActivityIndicator
      - ProgressActivityIndicatorView
      - ProgressFailureIndicator
      - ProgressFailureIndicatorView
      - ProgressImageIndicator
      - ProgressImageIndicatorView
      - ProgressPercentageIndicator
      - ProgressPercentageIndicatorView
      - ProgressSpinnerIndicator
      - ProgressSpinnerIndicatorView
      - ProgressSuccessIndicator
      - ProgressSuccessIndicatorView

  - name: MediaPicker
    children:
      - MediaPicker
      - MediaPickerSource
      - MediaPickerType
      - MediaPickerCameraSettings
      - MediaPickerImageExportPreset
      - MediaPickerResult
      - ScreenShowMediaPickerAction
      - MediaPickerSourceAccessDeniedError
      - UnavailableMediaPickerSourceError
      - UnavailableMediaPickerTypesError

  - name: Safari
    children:
      - Safari
      - ScreenShowSafariAction
      - InvalidSafariURLError

  - name: Sharing
    children:
      - Sharing
      - SharingItem
      - SharingCustomItem
      - SharingActivity
      - SharingActivityCategory
      - SharingActivityType
      - SharingCustomActivity
      - SharingSilentActivity
      - SharingVisualActivity
      - ScreenShareAction

  - name: StoreProduct
    children:
      - StoreProduct
      - ScreenShowStoreProductAction
      - InvalidStoreProductIDError

  - name: StoreReview
    children:
      - ScreenRequestStoreReviewAction

  - name: URL
    children:
      - ScreenOpenURLAction
      - FailedToOpenURLError

  - name: Call
    children:
      - ScreenCallAction
      - InvalidCallParametersError

  - name: Mail
    children:
      - ScreenMailAction
      - InvalidMailParametersError

  - name: OpenSettings
    children:
      - ScreenOpenSettingsAction
      - InvalidOpenSettingsURLError

  - name: OpenStoreApp
    children:
      - ScreenOpenStoreAppAction
      - InvalidStoreAppIDError
