included:
  - Example
  - Sources
  - Tests

excluded:
  - "*/Pods"

analyzer_rules:
  - capture_variable
  - typesafe_array_init
  - unused_declaration
  - unused_import

only_rules:
  - accessibility_label_for_image
  - accessibility_trait_for_button
  - anonymous_argument_in_multiline_closure
  - array_init
  - attributes
  - blanket_disable_command
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_body_length
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - comma_inheritance
  - comment_spacing
  - compiler_protocol_init
  - computed_accessors_order
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - control_statement
  - convenience_type
  - custom_rules
  - cyclomatic_complexity
  - direct_return
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_direct_init
  - discouraged_object_literal
  - duplicate_conditions
  - duplicate_enum_cases
  - duplicate_imports
  - duplicated_key_in_dictionary_literal
  - dynamic_inline
  - empty_collection_literal
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_acl
  - explicit_init
  - explicit_top_level_acl
  - fatal_error_message
  - file_header
  - file_length
  - file_name
  - file_types_order
  - first_where
  - flatmap_over_map_reduce
  - for_where
  - force_try
  - function_body_length
  - function_parameter_count
  - generic_type_name
  - ibinspectable_in_extension
  - identical_operands
  - identifier_name
  - implicit_getter
  - implicit_return
  - implicitly_unwrapped_optional
  - inclusive_language
  - indentation_width
  - invalid_swiftlint_command
  - is_disjoint
  - joined_default_parameter
  - large_tuple
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_multiple
  - legacy_nsgeometry_functions
  - legacy_random
  - let_var_whitespace
  - line_length
  - literal_expression_end_indentation
  - local_doc_comment
  - lower_acl_than_parent
  - mark
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - multiple_closures_with_trailing_closure
  - nesting
  - no_extension_access_modifier
  - no_fallthrough_only
  - no_space_in_method_call
  - ns_number_init_as_function_reference
  - nsobject_prefer_isequal
  - number_separator
  - opening_brace
  - operator_whitespace
  - operator_usage_whitespace
  - optional_enum_case_matching
  - orphaned_doc_comment
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - period_spacing
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - private_over_fileprivate
  - private_subject
  - private_unit_test
  - prohibited_interface_builder
  - prohibited_super_call
  - protocol_property_accessors_order
  - raw_value_for_camel_cased_codable_enum
  - reduce_boolean
  - reduce_into
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_self_in_closure
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_type_annotation
  - redundant_void_return
  - return_arrow_whitespace
  - self_binding
  - self_in_property_initialization
  - shorthand_operator
  - shorthand_optional_binding
  - single_test_class
  - sorted_first_last
  - statement_position
  - static_operator
  - superfluous_disable_command
  - superfluous_else
  - switch_case_alignment
  - switch_case_on_newline
  - syntactic_sugar
  - todo
  - toggle_bool
  - trailing_closure
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
  - type_contents_order
  - type_name
  - unavailable_condition
  - unavailable_function
  - unhandled_throwing_task
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_enumerated
  - unused_optional_binding
  - unused_setter_value
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - void_function_in_ternary
  - void_return
  - weak_delegate
  - xctfail_message
  - xct_specific_matcher
  - yoda_condition

attributes:
  always_on_same_line:
    - '@dynamic'
    - '@GKInspectable'
    - '@IBAction'
    - '@IBDesignable'
    - '@IBInspectable'
    - '@IBOutlet'
    - '@nonobjc'
    - '@NSCopying'
    - '@NSManaged'
    - '@objc'
    - '@objcMembers'
    - '@testable'
  always_on_line_above:
    - '@available'
    - '@convention'
    - '@discardableResult'
    - '@dynamicCallable'
    - '@dynamicMemberLookup'
    - '@frozen'
    - '@inlinable'
    - '@MainActor'
    - '@NSApplicationMain'
    - '@propertyWrapper'
    - '@requires_stored_property_inits'
    - '@UIApplicationMain'
    - '@usableFromInline'
    - '@warn_unqualified_access'

blanket_disable_command:
  allowed_rules: []
  always_blanket_disable:
    - file_header
    - file_length
    - file_name
    - file_name_no_space
    - file_types_order
    - single_test_class

closure_body_length:
  warning: 30
  error: 300

collection_alignment:
  align_colons: false

colon:
  flexible_right_spacing: true
  apply_to_dictionaries: true

conditional_returns_on_newline:
  if_only: false

cyclomatic_complexity:
  warning: 16
  error: 160
  ignores_case_statements: true

discouraged_direct_init:
  types:
    - AVAudioSession
    - Bundle
    - NSError
    - UIDevice

discouraged_object_literal:
  image_literal: true
  color_literal: true

duplicate_conditions:
  severity: warning

duplicate_enum_cases:
  severity: warning

dynamic_inline:
  severity: warning

empty_count:
  severity: warning
  only_after_dot: false

empty_xctest_method:
  test_parent_classes:
    - XCTestCase
    - QuickSpec

enum_case_associated_values_count:
  warning: 6
  error: 60

file_header:
  forbidden_pattern: ".?"

file_length:
  warning: 500
  error: 5000
  ignore_comment_only_lines: true

file_name:
  excluded:
    - main.swift
  prefix_pattern: ''
  suffix_pattern: '[+][A-z][A-z]+'
  nested_type_separator: ''

file_types_order:
  order:
    - main_type
    - extension
    - preview_provider
    - library_content_provider

force_try:
  severity: warning

function_body_length:
  warning: 40
  error: 400

function_parameter_count:
  warning: 6
  error: 60
  ignores_default_parameters: false

generic_type_name:
  min_length:
    warning: 3
    error: 0
  max_length:
    warning: 20
    error: 200
  excluded:
    - T
    - U
    - V
  allowed_symbols: []
  validates_start_with_lowercase: warning

identifier_name:
  min_length:
    warning: 2
    error: 0
  max_length:
    warning: 50
    error: 500
  excluded:
    - a
    - r
    - g
    - b
    - i
    - j
    - x
    - y
    - z
    - w
  allowed_symbols: []
  validates_start_with_lowercase: warning

implicit_return:
  included:
    - closure
    - function
    - getter

implicitly_unwrapped_optional:
  mode: all_except_iboutlets

indentation_width:
  indentation_width: 4
  include_comments: true
  include_compiler_directives: true
  include_multiline_strings: false

large_tuple:
  warning: 3
  error: 30

line_length:
  warning: 120
  error: 1200
  ignores_urls: true
  ignores_function_declarations: false
  ignores_comments: false
  ignores_interpolated_strings: false

modifier_order:
  preferred_modifier_order:
    - acl
    - setterACL
    - override
    - owned
    - mutators
    - final
    - typeMethods
    - required
    - convenience
    - lazy
    - dynamic

multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: false

nesting:
  type_level:
    warning: 1
    error: 10
  function_level:
    warning: 2
    error: 20
  check_nesting_in_closures_and_statements: true
  always_allow_one_type_in_functions: false

no_extension_access_modifier:
  severity: warning

number_separator:
  minimum_length: 5
  minimum_fraction_length: 5
  exclude_ranges: []

opening_brace:
  allow_multiline_func: false

operator_usage_whitespace:
  lines_look_around: 2
  skip_aligned_constants: false
  allowed_no_space_operators:
    - '...'
    - '..<'

overridden_super_call:
  included:
    - '*'
  excluded: []

private_outlet:
  allow_private_set: false

private_over_fileprivate:
  validate_extensions: true

prohibited_super_call:
  included:
    - '*'
  excluded: []

self_binding:
  bind_identifier: self

shorthand_operator:
  severity: warning

single_test_class:
  test_parent_classes:
    - XCTestCase
    - QuickSpec

statement_position:
  statement_mode: default

switch_case_alignment:
  indented_cases: false

trailing_closure:
  only_single_muted_parameter: false

trailing_comma:
  mandatory_comma: false

trailing_whitespace:
  ignores_empty_lines: false
  ignores_comments: false

type_body_length:
  warning: 450
  error: 4500

type_contents_order:
  order:
    - associated_type
    - type_alias
    - subtype
    - case
    - type_property
    - type_method
    - ib_outlet
    - ib_inspectable
    - instance_property
    - initializer
    - deinitializer
    - ib_action
    - other_method
    - view_life_cycle_method
    - subscript

type_name:
  min_length:
    warning: 3
    error: 0
  max_length:
    warning: 50
    error: 500
  excluded: []
  allowed_symbols: []
  validates_start_with_lowercase: warning
  validate_protocols: true

unused_declaration:
  severity: warning
  include_public_and_open: false

unused_import:
  require_explicit_imports: false
  allowed_transitive_imports: []
  always_keep_imports: []

unused_optional_binding:
  ignore_optional_try: false

vertical_whitespace:
  max_empty_lines: 1

vertical_whitespace_closing_braces:
  only_enforce_before_trivial_lines: false

xct_specific_matcher:
  matchers:
    - one-argument-asserts
    - two-argument-asserts

warning_threshold: 100
